### ISSUE TITLE
兄弟～ 这个方法可行性咋样？

### ISSUE THREAD

**Issue by t0rjan** [Charleswyt/crawler#1]

**Comment by Charleswyt** [comment]
> _No description provided._

类似于手工点击的批处理脚本，实测速度和安全性还行

**Comment by t0rjan** [comment]
@Charleswyt 被封频繁嘛？以及这个脚本失效性？

**Comment by Charleswyt** [comment]
> @Charleswyt 被封频繁嘛？以及这个�脚本失效性？

- 安全性还是可以的，设置好时间间隔基本不会被封
- 脚本是去年四五月开发的，到今年六七月还可以用

**Comment by t0rjan** [comment]
thanks u.
